# Google App Engine configuration for Synapse-Lang Platform
runtime: python39
instance_class: F2

env_variables:
  PROJECT_ID: "industrial-joy-456916-a2"
  FLASK_ENV: "production"
  STRIPE_PUBLISHABLE_KEY: "pk_live_YOUR_STRIPE_KEY"

handlers:
- url: /static
  static_dir: synapse-lang.com/static
  secure: always

- url: /branding
  static_dir: branding
  secure: always

- url: /playground/static
  static_dir: playground/static
  secure: always

- url: /crowehub/static
  static_dir: crowehub/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

vpc_access_connector:
  name: projects/industrial-joy-456916-a2/locations/us-central1/connectors/synapse-connector

inbound_services:
- warmup