# Cloud Build configuration for industrial-joy-456916-a2
steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']

  # Run tests
  - name: 'python:3.9'
    entrypoint: python
    args: ['test_synapse.py']

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - '--project=industrial-joy-456916-a2'
      - '--quiet'

  # Deploy dispatch configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'dispatch.yaml'
      - '--project=industrial-joy-456916-a2'
      - '--quiet'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'