version: '3.8'

services:
  # Main Synapse development environment
  synapse-dev:
    image: synapse-lang/synapse-lang:2.3.0
    container_name: synapse-dev
    volumes:
      - ./workspace:/workspace
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"  # Jupyter
      - "5000:5000"  # API server (if needed)
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SYNAPSE_ENV=development
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --notebook-dir=/workspace
    networks:
      - synapse-network

  # Distributed computing worker node 1
  synapse-worker-1:
    image: synapse-lang/synapse-lang:2.3.0
    container_name: synapse-worker-1
    volumes:
      - ./workspace:/workspace
    environment:
      - WORKER_ID=worker-1
      - MASTER_HOST=synapse-master
    depends_on:
      - synapse-master
    networks:
      - synapse-network

  # Distributed computing worker node 2
  synapse-worker-2:
    image: synapse-lang/synapse-lang:2.3.0
    container_name: synapse-worker-2
    volumes:
      - ./workspace:/workspace
    environment:
      - WORKER_ID=worker-2
      - MASTER_HOST=synapse-master
    depends_on:
      - synapse-master
    networks:
      - synapse-network

  # Master node for distributed computing
  synapse-master:
    image: synapse-lang/synapse-lang:2.3.0
    container_name: synapse-master
    volumes:
      - ./workspace:/workspace
    ports:
      - "8080:8080"  # Master API
    environment:
      - ROLE=master
      - WORKERS=2
    networks:
      - synapse-network

  # Collaboration server
  synapse-collab:
    image: synapse-lang/synapse-lang:2.3.0
    container_name: synapse-collab
    volumes:
      - ./workspace:/workspace
    ports:
      - "3000:3000"  # WebSocket server
    environment:
      - SERVICE=collaboration
    networks:
      - synapse-network

networks:
  synapse-network:
    driver: bridge

volumes:
  workspace:
  notebooks: