site_name: Synapse Language Documentation
site_description: A quantum-enhanced programming language for scientific computing
site_author: Synapse Development Team
site_url: https://synapse-lang.org
repo_url: https://github.com/MichaelCrowe11/synapse-lang
repo_name: synapse-lang

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
    
  icon:
    repo: fontawesome/brands/github
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - stylesheets/extra.css
  
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Hello World: getting-started/hello-world.md
    - IDE Setup: getting-started/ide-setup.md
    
  - Language Guide:
    - Syntax Overview: language/syntax.md
    - Data Types: language/data-types.md
    - Variables & Constants: language/variables.md
    - Control Flow: language/control-flow.md
    - Functions: language/functions.md
    - Parallel Execution: language/parallel.md
    - Error Handling: language/errors.md
    
  - Scientific Computing:
    - Hypothesis Testing: scientific/hypothesis.md
    - Experiments: scientific/experiments.md
    - Uncertainty Quantification: scientific/uncertainty.md
    - Tensor Operations: scientific/tensors.md
    - Symbolic Math: scientific/symbolic.md
    - Reasoning Chains: scientific/reasoning.md
    
  - Quantum Computing:
    - Quantum Basics: quantum/basics.md
    - Quantum Circuits: quantum/circuits.md
    - Quantum Algorithms: quantum/algorithms.md
    - Quantum-Classical Hybrid: quantum/hybrid.md
    - Simulators & Backends: quantum/backends.md
    
  - Machine Learning:
    - ML Integration: ml/integration.md
    - Neural Networks: ml/neural-networks.md
    - AutoML: ml/automl.md
    - Model Deployment: ml/deployment.md
    
  - API Reference:
    - Core API: api/core.md
    - Quantum API: api/quantum.md
    - Tensor API: api/tensor.md
    - Scientific API: api/scientific.md
    - Security API: api/security.md
    
  - Examples:
    - Scientific Examples: examples/scientific.md
    - Quantum Examples: examples/quantum.md
    - ML Examples: examples/ml.md
    - Drug Discovery: examples/drug-discovery.md
    - Climate Modeling: examples/climate.md
    
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Building from Source: development/building.md
    - Plugin Development: development/plugins.md
    
  - Community:
    - Discord: https://discord.gg/synapse-lang
    - GitHub: https://github.com/MichaelCrowe11/synapse-lang
    - Forum: https://forum.synapse-lang.org
    - Blog: https://blog.synapse-lang.org
    
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaelCrowe11/synapse-lang
    - icon: fontawesome/brands/discord
      link: https://discord.gg/synapse-lang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/synapselang
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/synapse-lang
      
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      
copyright: Copyright &copy; 2024 Synapse Language - <a href="#__consent">Change cookie settings</a>