line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "UP", "B", "Q", "W"]
ignore = ["E203", "E266", "E501"]

[lint.per-file-ignores]
"tests/*" = ["B011"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"