package:
  name: synapse-lang
  version: 2.2.0

source:
  url: https://pypi.io/packages/source/s/synapse-lang/synapse-lang-2.2.0.tar.gz
  sha256: PLACEHOLDER

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19
    - scipy >=1.5

test:
  imports:
    - synapse_lang
  commands:
    - python -c "from synapse_lang import __version__"

about:
  home: https://synapse-lang.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scientific programming language with uncertainty and quantum support
  description: |
    Synapse is a domain-specific language for scientific computing with
    native support for uncertainty propagation, quantum computing, and
    parallel execution.
  doc_url: https://docs.synapse-lang.org
  dev_url: https://github.com/synapse-lang/synapse-lang

extra:
  recipe-maintainers:
    - synapse-team
